# Numpy Basics

In [6]:
import numpy
numpy.__version__

'1.24.2'

In [7]:
import numpy as np

In [8]:
np?

Type:        module
String form: <module 'numpy' from 'c:\\Users\\rcpsi\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\rcpsi\appdata\local\programs\python\python311\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets

In [10]:
x = [1,4,2,5,3]

In [12]:
type(x[0])

int

In [22]:
x = np.array(x,dtype='int16')

In [23]:
x

array([1, 4, 2, 5, 3], dtype=int16)

In [24]:
type(x)

numpy.ndarray

In [25]:
type(x[0])

numpy.int16

In [26]:
x = np.array([3.14,4,2,3])

In [27]:
type(x[1])

numpy.float64

In [28]:
x = np.array([3.14,4,2,3],'float32')

In [29]:
type(x[0])

numpy.float32

## Pre-allocation

In [30]:
x = np.zeros(10,dtype=int)

In [31]:
x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [40]:
x = np.ones((3,4),dtype=float)
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
x = np.full((3,4),3.14)
x

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [42]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [43]:
x = np.arange(5,20)
x

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [44]:
x = np.arange(0,20,2)
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [46]:
x = np.linspace(0,1,5)
x

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [48]:
x = np.random.random((3,3))
x

array([[0.30814546, 0.16658484, 0.98428596],
       [0.43635921, 0.59257963, 0.45946453],
       [0.51402426, 0.15542036, 0.33142484]])

In [50]:
x = np.random.normal(0,1,(4,3))
x

array([[ 0.59719423, -1.64405531, -0.56553342],
       [ 1.04549476,  0.15630509,  0.76710821],
       [-0.60770794, -1.5218967 , -0.0652083 ],
       [-1.33823609,  0.22512629,  0.47944994]])

In [51]:
np.random.normal?

Docstring:
normal(loc=0.0, scale=1.0, size=None)

Draw random samples from a normal (Gaussian) distribution.

The probability density function of the normal distribution, first
derived by De Moivre and 200 years later by both Gauss and Laplace
independently [2]_, is often called the bell curve because of
its characteristic shape (see the example below).

The normal distributions occurs often in nature.  For example, it
describes the commonly occurring distribution of samples influenced
by a large number of tiny, random disturbances, each with its own
unique distribution [2]_.

.. note::
    New code should use the `~numpy.random.Generator.normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
loc : float or array_like of floats
    Mean ("centre") of the distribution.
scale : float or array_like of floats
    Standard deviation (spread or "width") of the distribution. Must be
    non-negative.
size : int 

In [54]:
x = np.random.randint(0,10,(3,3,3))
x

array([[[1, 4, 4],
        [3, 9, 2],
        [6, 1, 8]],

       [[6, 1, 4],
        [5, 6, 3],
        [9, 8, 4]],

       [[5, 6, 7],
        [2, 8, 7],
        [7, 6, 2]]])

In [53]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [55]:
x1 = np.random.randint(10,size=(6))
x2 = np.random.randint(10,size=(3,4))
x3 = np.random.randint(10,size=(3,4,5))

In [60]:
print(f'x3 ndim: {x3.ndim}')

x3 ndim: 3


In [62]:
print(f'x3 shape: {x3.shape}')

x3 shape: (3, 4, 5)


In [63]:
print(f'x3 size: {x3.size}')

x3 size: 60


In [64]:
print(f'itemsize: {x3.itemsize} bytes')

itemsize: 4 bytes


In [65]:
type(x3[0,0,0])

numpy.int32

In [66]:
print(f'nbytes: {x3.nbytes} bytes')

nbytes: 240 bytes


In [67]:
x1

array([8, 3, 3, 9, 5, 8])

In [68]:
x1[0]

8

In [69]:
x2

array([[6, 5, 9, 9],
       [9, 7, 4, 5],
       [7, 6, 9, 5]])

In [70]:
x2[0,1]

5

In [71]:
x1

array([8, 3, 3, 9, 5, 8])

In [72]:
x1[-1]

8

In [73]:
x1[-2]

5

In [74]:
x2

array([[6, 5, 9, 9],
       [9, 7, 4, 5],
       [7, 6, 9, 5]])

In [75]:
x2[0,-1]

9

In [76]:
x2[-1,-3]

6

## Array Slicing

In [78]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

x[inicio:fim:incremento]

In [79]:
x[:5]

array([0, 1, 2, 3, 4])

In [80]:
x[0:5]

array([0, 1, 2, 3, 4])

In [81]:
x[5:]

array([5, 6, 7, 8, 9])

In [82]:
x[4:7]

array([4, 5, 6])

In [83]:
x[::2]

array([0, 2, 4, 6, 8])

In [84]:
x[1::2]

array([1, 3, 5, 7, 9])

In [85]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [86]:
x[5::-2]

array([5, 3, 1])

In [87]:
x2

array([[6, 5, 9, 9],
       [9, 7, 4, 5],
       [7, 6, 9, 5]])

In [88]:
x2[:2,:]

array([[6, 5, 9, 9],
       [9, 7, 4, 5]])

In [89]:
x2[:2,:2]

array([[6, 5],
       [9, 7]])

In [90]:
x2[:2,::2]

array([[6, 9],
       [9, 4]])

In [91]:
x2[::-1,::-1]

array([[5, 9, 6, 7],
       [5, 4, 7, 9],
       [9, 9, 5, 6]])

In [93]:
x2

array([[6, 5, 9, 9],
       [9, 7, 4, 5],
       [7, 6, 9, 5]])

In [92]:
x2[:,2]

array([9, 4, 9])

In [94]:
x2[1,:]

array([9, 7, 4, 5])

In [95]:
x2[1]

array([9, 7, 4, 5])

In [96]:
x2

array([[6, 5, 9, 9],
       [9, 7, 4, 5],
       [7, 6, 9, 5]])

## Views

In [97]:
x2

array([[6, 5, 9, 9],
       [9, 7, 4, 5],
       [7, 6, 9, 5]])

In [99]:
x2_slice = x2[:2,:2]

In [100]:
x2_slice

array([[6, 5],
       [9, 7]])

In [101]:
x2_slice[0,0] = 100

In [102]:
x2_slice

array([[100,   5],
       [  9,   7]])

In [103]:
x2

array([[100,   5,   9,   9],
       [  9,   7,   4,   5],
       [  7,   6,   9,   5]])

In [104]:
x2_slice = x2[:2,:2].copy()

In [105]:
x2_slice

array([[100,   5],
       [  9,   7]])

In [107]:
x2_slice[0,0] = 0
x2_slice

array([[0, 5],
       [9, 7]])

In [108]:
x2

array([[100,   5,   9,   9],
       [  9,   7,   4,   5],
       [  7,   6,   9,   5]])

## Exercícios

1. Crie uma função que receba uma lista como argumento e retorne o número de elementos da lista.