# Numpy Basics

In [6]:
import numpy
numpy.__version__

'1.24.2'

In [7]:
import numpy as np

In [8]:
np?

Type:        module
String form: <module 'numpy' from 'c:\\Users\\rcpsi\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\rcpsi\appdata\local\programs\python\python311\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets

In [10]:
x = [1,4,2,5,3]

In [12]:
type(x[0])

int

In [22]:
x = np.array(x,dtype='int16')

In [23]:
x

array([1, 4, 2, 5, 3], dtype=int16)

In [24]:
type(x)

numpy.ndarray

In [25]:
type(x[0])

numpy.int16

In [26]:
x = np.array([3.14,4,2,3])

In [27]:
type(x[1])

numpy.float64

In [28]:
x = np.array([3.14,4,2,3],'float32')

In [29]:
type(x[0])

numpy.float32

## Pre-allocation

In [30]:
x = np.zeros(10,dtype=int)

In [31]:
x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [40]:
x = np.ones((3,4),dtype=float)
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
x = np.full((3,4),3.14)
x

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [42]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [43]:
x = np.arange(5,20)
x

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [44]:
x = np.arange(0,20,2)
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [46]:
x = np.linspace(0,1,5)
x

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [48]:
x = np.random.random((3,3))
x

array([[0.30814546, 0.16658484, 0.98428596],
       [0.43635921, 0.59257963, 0.45946453],
       [0.51402426, 0.15542036, 0.33142484]])

In [50]:
x = np.random.normal(0,1,(4,3))
x

array([[ 0.59719423, -1.64405531, -0.56553342],
       [ 1.04549476,  0.15630509,  0.76710821],
       [-0.60770794, -1.5218967 , -0.0652083 ],
       [-1.33823609,  0.22512629,  0.47944994]])

In [51]:
np.random.normal?

Docstring:
normal(loc=0.0, scale=1.0, size=None)

Draw random samples from a normal (Gaussian) distribution.

The probability density function of the normal distribution, first
derived by De Moivre and 200 years later by both Gauss and Laplace
independently [2]_, is often called the bell curve because of
its characteristic shape (see the example below).

The normal distributions occurs often in nature.  For example, it
describes the commonly occurring distribution of samples influenced
by a large number of tiny, random disturbances, each with its own
unique distribution [2]_.

.. note::
    New code should use the `~numpy.random.Generator.normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
loc : float or array_like of floats
    Mean ("centre") of the distribution.
scale : float or array_like of floats
    Standard deviation (spread or "width") of the distribution. Must be
    non-negative.
size : int 

In [54]:
x = np.random.randint(0,10,(3,3,3))
x

array([[[1, 4, 4],
        [3, 9, 2],
        [6, 1, 8]],

       [[6, 1, 4],
        [5, 6, 3],
        [9, 8, 4]],

       [[5, 6, 7],
        [2, 8, 7],
        [7, 6, 2]]])

In [53]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [55]:
x1 = np.random.randint(10,size=(6))
x2 = np.random.randint(10,size=(3,4))
x3 = np.random.randint(10,size=(3,4,5))

In [60]:
print(f'x3 ndim: {x3.ndim}')

x3 ndim: 3


In [62]:
print(f'x3 shape: {x3.shape}')

x3 shape: (3, 4, 5)


In [63]:
print(f'x3 size: {x3.size}')

x3 size: 60


In [64]:
print(f'itemsize: {x3.itemsize} bytes')

itemsize: 4 bytes


In [65]:
type(x3[0,0,0])

numpy.int32

In [66]:
print(f'nbytes: {x3.nbytes} bytes')

nbytes: 240 bytes


In [67]:
x1

array([8, 3, 3, 9, 5, 8])

In [68]:
x1[0]

8

In [69]:
x2

array([[6, 5, 9, 9],
       [9, 7, 4, 5],
       [7, 6, 9, 5]])

In [70]:
x2[0,1]

5

In [71]:
x1

array([8, 3, 3, 9, 5, 8])

In [72]:
x1[-1]

8

In [73]:
x1[-2]

5

In [74]:
x2

array([[6, 5, 9, 9],
       [9, 7, 4, 5],
       [7, 6, 9, 5]])

In [75]:
x2[0,-1]

9

In [76]:
x2[-1,-3]

6

## Array Slicing

In [78]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

x[inicio:fim:incremento]

In [79]:
x[:5]

array([0, 1, 2, 3, 4])

In [80]:
x[0:5]

array([0, 1, 2, 3, 4])

In [81]:
x[5:]

array([5, 6, 7, 8, 9])

In [82]:
x[4:7]

array([4, 5, 6])

In [83]:
x[::2]

array([0, 2, 4, 6, 8])

In [84]:
x[1::2]

array([1, 3, 5, 7, 9])

In [85]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [86]:
x[5::-2]

array([5, 3, 1])

In [87]:
x2

array([[6, 5, 9, 9],
       [9, 7, 4, 5],
       [7, 6, 9, 5]])

In [88]:
x2[:2,:]

array([[6, 5, 9, 9],
       [9, 7, 4, 5]])

In [89]:
x2[:2,:2]

array([[6, 5],
       [9, 7]])

In [90]:
x2[:2,::2]

array([[6, 9],
       [9, 4]])

In [91]:
x2[::-1,::-1]

array([[5, 9, 6, 7],
       [5, 4, 7, 9],
       [9, 9, 5, 6]])

In [93]:
x2

array([[6, 5, 9, 9],
       [9, 7, 4, 5],
       [7, 6, 9, 5]])

In [92]:
x2[:,2]

array([9, 4, 9])

In [94]:
x2[1,:]

array([9, 7, 4, 5])

In [95]:
x2[1]

array([9, 7, 4, 5])

In [96]:
x2

array([[6, 5, 9, 9],
       [9, 7, 4, 5],
       [7, 6, 9, 5]])

## Views

In [97]:
x2

array([[6, 5, 9, 9],
       [9, 7, 4, 5],
       [7, 6, 9, 5]])

In [99]:
x2_slice = x2[:2,:2]

In [100]:
x2_slice

array([[6, 5],
       [9, 7]])

In [101]:
x2_slice[0,0] = 100

In [102]:
x2_slice

array([[100,   5],
       [  9,   7]])

In [103]:
x2

array([[100,   5,   9,   9],
       [  9,   7,   4,   5],
       [  7,   6,   9,   5]])

In [104]:
x2_slice = x2[:2,:2].copy()

In [105]:
x2_slice

array([[100,   5],
       [  9,   7]])

In [107]:
x2_slice[0,0] = 0
x2_slice

array([[0, 5],
       [9, 7]])

In [108]:
x2

array([[100,   5,   9,   9],
       [  9,   7,   4,   5],
       [  7,   6,   9,   5]])

## Exercícios

1. Crie uma função que receba uma lista como argumento e retorne o número de elementos da lista.

In [110]:
def nelementos(L):
    return len(L)

x = [1,2,3,4]
nelementos(x)

4

2. Utilize o comando "%xmode" para mudar o modo de depuração para "Plain" e execute o código abaixo. Observe como o traceback é apresentado.

In [111]:
def imprime_elementos(lista):
    for i in range(len(lista)):
        print(lista[i+1])

lista = [1, 2, 3, 4, 5]
imprime_elementos(lista)

2
3
4
5


IndexError: list index out of range

In [112]:
%xmode plain

Exception reporting mode: Plain


In [113]:
imprime_elementos(lista)

2
3
4
5


IndexError: list index out of range

3. Utilize o comando "%xmode" para mudar o modo de depuração para "Verbose" e execute a mesma função do exercício anterior. Indentifique a causa do problema.

In [114]:
%xmode verbose

Exception reporting mode: Verbose


In [115]:
imprime_elementos(lista)

2
3
4
5


IndexError: list index out of range

4. Crie um array numpy unidimensional de tamanho 10, contendo apenas números pares.

In [116]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

5. Crie um array numpy bidimensional de tamanho (3, 3), contendo apenas números inteiros aleatórios entre 0 e 9.

In [119]:
np.random.randint(0,10,(3,3))

array([[0, 0, 1],
       [7, 7, 8],
       [9, 6, 0]])

6. Crie um array numpy unidimensional de tamanho 20, contendo números aleatórios entre 0 e 1, e em seguida, calcule a soma dos elementos nas posições ímpares.

In [134]:
x = np.random.random(20)
x

array([0.21285567, 0.66995082, 0.36028531, 0.42142089, 0.16871259,
       0.12007205, 0.51847939, 0.35450636, 0.18932504, 0.9800424 ,
       0.68954158, 0.00684362, 0.67416517, 0.06764829, 0.52331729,
       0.4126415 , 0.17013856, 0.64142351, 0.69207092, 0.10231686])

In [135]:
x = x[1::2].copy()
x

array([0.66995082, 0.42142089, 0.12007205, 0.35450636, 0.9800424 ,
       0.00684362, 0.06764829, 0.4126415 , 0.64142351, 0.10231686])

In [136]:
np.sum(x)

3.7768662863320297

In [129]:
x = np.random.normal(0,1,1000)
x

array([-7.80793061e-01,  1.21322522e+00,  2.13606277e+00,  9.82795533e-01,
        9.12707658e-01, -4.60795114e-02, -8.08776998e-01,  6.86090014e-01,
       -2.40552183e-01, -5.47150444e-01, -1.21040743e-02, -1.39332053e+00,
        1.96014895e+00,  5.91517001e-01,  3.75644401e-01,  1.68685550e+00,
        1.56518035e-01, -1.49496426e-01, -1.74097410e+00, -3.36904517e-01,
        8.08166738e-01,  1.99501663e+00,  4.15185665e-01,  5.74159379e-01,
        1.29531112e+00,  1.67100515e-01,  7.84839501e-01,  9.45914909e-01,
       -3.00554431e+00, -8.82813055e-01,  9.49007426e-03, -2.62748942e-03,
       -2.51086762e+00, -4.09423265e-01, -1.68367127e+00,  7.87183414e-01,
        2.53305325e-01,  1.96739212e-01,  1.49301036e-01, -9.86649044e-01,
       -6.46913111e-01, -3.61064159e-01, -8.64138673e-01,  7.30257044e-01,
       -4.98694927e-01, -4.48338627e-01,  1.34425876e-01, -1.23107626e+00,
        2.02057055e+00,  1.87672064e+00,  1.93485590e+00,  5.11556887e-03,
       -5.74874565e-01,  

In [130]:
np.mean(x)

-0.008754968156222603

In [131]:
np.std(x)

0.981391873837298