# Computations with numpy

In [1]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
print(values)
print(compute_reciprocals(values))

[6 1 4 4 8]
[0.16666667 1.         0.25       0.25       0.125     ]


In [2]:
1/values

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [3]:
big_array = np.random.randint(1,100,1000000)
%timeit compute_reciprocals(big_array)

2.8 s ± 480 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
%timeit 1/big_array

6.1 ms ± 1.46 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
x = np.arange(5)
y = np.arange(1,6)

print(x)
print(y)
print(x/y)

[0 1 2 3 4]
[1 2 3 4 5]
[0.         0.5        0.66666667 0.75       0.8       ]


|Operator|	Equivalent ufunc |	Description |
|---:|:-------------| :-------------|
|+ |	np.add|	Addition (e.g., 1 + 1 = 2) |
|- |	np.subtract |	Subtraction (e.g., 3 - 2 = 1) |
|- |	np.negative |	Unary negation (e.g., -2) |
|* |	np.multiply |	Multiplication (e.g., 2 * 3 = 6)|
|/ |	np.divide |	Division (e.g., 3 / 2 = 1.5)|
|// |	np.floor_divide |	Floor division (e.g., 3 // 2 = 1)|
|** |	np.power |	Exponentiation (e.g., 2 ** 3 = 8)|
|% |	np.mod |	Modulus/remainder (e.g., 9 % 4 = 1)|

## Agreggates

In [6]:
x = np.arange(1,10)
print(x)
print(np.add.reduce(x))

[1 2 3 4 5 6 7 8 9]
45


In [7]:
np.multiply.reduce(x)

362880

In [8]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [9]:
np.multiply.accumulate(x)

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880])

In [10]:
x = np.arange(1,5)
y = np.arange(5,9)

In [11]:
x

array([1, 2, 3, 4])

In [12]:
np.multiply.outer(x,y)

array([[ 5,  6,  7,  8],
       [10, 12, 14, 16],
       [15, 18, 21, 24],
       [20, 24, 28, 32]])

In [13]:
L = np.random.random(100)

In [14]:
np.add.reduce(L)

50.46175845319564

In [15]:
np.sum(L)

50.46175845319564

In [16]:
big_array = np.random.randint(1,100,1000000)
%timeit np.sum(big_array)
%timeit sum(big_array)

772 µs ± 247 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
101 ms ± 21.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [17]:
np.min(L)

0.017651866638478286

In [18]:
np.max(L)

0.9966328433976568

In [19]:
%timeit min(big_array)
%timeit np.min(big_array)

92.6 ms ± 16.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
279 µs ± 99.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


# Exercícios

Problem 1: Working with NumPy Arrays

Given an array x of integers from 1 to 9, compute the sum of all the even numbers in the array.

In [20]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
evens = x[1:10:2]
evens

array([2, 4, 6, 8])

In [22]:
np.sum(evens)

20

Problem 2: Matrix Operations with NumPy

Given two matrices A and B, compute the product of the two matrices using NumPy.

In [23]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [24]:
C = np.dot(A,B)
C

array([[19, 22],
       [43, 50]])

## Multi-dimensional aggregates

In [25]:
M = np.random.randint(0,9,(3,4))
M

array([[5, 4, 3, 0],
       [4, 5, 2, 2],
       [4, 1, 7, 5]])

In [26]:
M.sum()

42

In [27]:
M.sum(axis=0)

array([13, 10, 12,  7])

In [28]:
M.sum(axis=1)

array([12, 13, 17])

In [29]:
M.mean(axis=0)

array([4.33333333, 3.33333333, 4.        , 2.33333333])

In [30]:
M.mean()

3.5

### Exercícios

Problem 1: Working with Random Numbers in NumPy

Create a NumPy array of size (4, 5) containing random integers between 1 and 10 (inclusive). Then, compute the maximum value in each column of the array.

In [31]:
rng = np.random
M = rng.randint(1,11,(4,5))
M

array([[10,  5,  7,  3,  3],
       [ 9, 10,  6,  4, 10],
       [ 4,  4,  8,  1,  5],
       [ 3,  6, 10,  9,  7]])

In [32]:
M.max(axis=0)

array([10, 10, 10,  9, 10])

Problem 2: Aggregation and Reduction in NumPy

Create a NumPy array of size (5, 6) containing random integers between 0 and 99 (inclusive). Then, compute the sum of all the elements in the array, the minimum value in each row of the array, and the maximum value in the entire array.

In [33]:
M = rng.randint(0,100,(5,6))

In [34]:
M.sum()

1464

In [35]:
M.min(axis=1)

array([ 3,  9, 27, 45, 37])

In [36]:
M.max()

99

In [37]:
M

array([[ 3, 12, 31,  8, 71, 98],
       [ 9, 46, 44, 39, 44, 10],
       [32, 97, 53, 36, 30, 27],
       [63, 68, 45, 92, 77, 47],
       [46, 57, 99, 64, 79, 37]])

## Other aggregations

|Function Name|	NaN-safe Version|	Description|
|:-----|:----------|:-------------|
|np.sum|	np.nansum|	Compute sum of elements|
|np.prod|	np.nanprod|	Compute product of elements|
|np.mean|	np.nanmean|	Compute mean of elements|
|np.std|	np.nanstd|	Compute standard deviation|
|np.var|	np.nanvar|	Compute variance|
|np.min|	np.nanmin|	Find minimum value|
|np.max|	np.nanmax|	Find maximum value|
|np.argmin|	np.nanargmin|	Find index of minimum value|
|np.argmax|	np.nanargmax|	Find index of maximum value|
|np.median|	np.nanmedian|	Compute median of elements|
|np.percentile|	np.nanpercentile|	Compute rank-based statistics of elements|
|np.any|	N/A|	Evaluate whether any elements are true|
|np.all|	N/A|	Evaluate whether all elements are true|

## Logical Operations

In [38]:
x = np.array([1,2,3,4,5])

In [39]:
x < 3

array([ True,  True, False, False, False])

In [40]:
x > 3

array([False, False, False,  True,  True])

In [41]:
x >= 3

array([False, False,  True,  True,  True])

In [42]:
x != 3

array([ True,  True, False,  True,  True])

In [43]:
x == 3

array([False, False,  True, False, False])

In [44]:
(2 * x) == (x ** 2) 

array([False,  True, False, False, False])

In [45]:
x ^ 2

array([3, 0, 1, 6, 7], dtype=int32)

In [46]:
x ** 2

array([ 1,  4,  9, 16, 25])

In [47]:
X = rng.randint(10,size=(3,4))
X

array([[3, 5, 5, 3],
       [4, 7, 7, 7],
       [5, 5, 4, 8]])

In [48]:
X < 6

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [ True,  True,  True, False]])

In [49]:
np.count_nonzero(X < 6)

8

In [50]:
(X<6).sum()

8

In [51]:
np.any(X < 6)

True

In [52]:
np.any(X>9)

False

In [53]:
np.all(X<6)

False

In [54]:
np.all(X<6,axis = 0)

array([ True, False, False, False])

## Boolean operations

In [55]:
x = rng.randint(20,size=(1,10))
x

array([[17,  4, 14,  0,  0, 12, 11,  8, 18,  9]])

In [56]:
(x >= 4) & (x<=10)

array([[False,  True, False, False, False, False, False,  True, False,
         True]])

In [57]:
np.sum((x >= 4) & (x<=10))

3

In [58]:
(x < 4) | (x > 10)

array([[ True, False,  True,  True,  True,  True,  True, False,  True,
        False]])

In [59]:
np.sum((x < 4) | (x > 10))

7

## Fancy indexing

In [60]:
x = rng.randint(100,size=(10))
x

array([93,  2, 94, 22, 61, 56, 73, 10, 51, 93])

In [61]:
x[[2,4,5]]

array([94, 61, 56])

In [62]:
x[x > 30]

array([93, 94, 61, 56, 73, 51, 93])

In [63]:
(x > 30) & (x < 60)

array([False, False, False, False, False,  True, False, False,  True,
       False])

In [64]:
x[(x > 30) & (x < 60)]

array([56, 51])

In [65]:
(x%2)==0

array([False,  True,  True,  True, False,  True, False,  True, False,
       False])

In [66]:
x[(x%2)==0]

array([ 2, 94, 22, 56, 10])

In [67]:
np.sum(x[(x%2)==0])

184

Encontrar os índices do números pares

In [68]:
x.size

10

In [69]:
idx = np.arange(x.size)
idx

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
x

array([93,  2, 94, 22, 61, 56, 73, 10, 51, 93])

In [71]:
(x%2)==0

array([False,  True,  True,  True, False,  True, False,  True, False,
       False])

In [72]:
idx[(x%2)==0]

array([1, 2, 3, 5, 7])

In [73]:
X = rng.randint(10,size=(3,4))
X

array([[1, 3, 1, 5],
       [1, 4, 7, 3],
       [5, 5, 3, 0]])

In [74]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
print(X[0,2])
print(X[1,1])
print(X[2,3])
print(X[row, col])

1
4
0
[1 4 0]


## Exercícios

Problem 1: Filtering Data in a NumPy Array

Create a NumPy array of random integers between 0 and 9 with shape (5, 5). Use NumPy's filtering capabilities to create a new array that only contains values less than 5.

In [75]:
x = np.random.randint(0,10,(5,5))
x

array([[1, 5, 5, 7, 7],
       [5, 6, 3, 8, 1],
       [6, 9, 6, 2, 4],
       [5, 0, 0, 5, 4],
       [3, 3, 8, 5, 4]])

In [76]:
nx = x[x<5]
nx

array([1, 3, 1, 2, 4, 0, 0, 4, 3, 3, 4])

Problem 2: Checking Conditions in a NumPy Array

Create a NumPy array of random integers between 0 and 9 with shape (4, 4). Use NumPy's boolean indexing to count how many values are greater than 5.

In [77]:
x = np.random.randint(0,10,(4,4))
x

array([[1, 7, 7, 1],
       [5, 0, 5, 2],
       [7, 3, 9, 0],
       [2, 7, 2, 9]])

In [78]:
x>5

array([[False,  True,  True, False],
       [False, False, False, False],
       [ True, False,  True, False],
       [False,  True, False,  True]])

In [79]:
np.count_nonzero(x>5)

6

In [80]:
np.sum(x>5)

6

Problema 3

Crie um array numpy aleatório com forma (10,) e substitua todos os elementos que são menores que a média do array por 0 e todos os outros elementos por 1.

In [81]:
x = rng.random(10)
x

array([0.01284936, 0.42455647, 0.6030984 , 0.8622993 , 0.65849341,
       0.95489476, 0.05124187, 0.63479552, 0.14377629, 0.68867759])

In [82]:
media = x.mean()
media

0.5034682977438341

In [83]:
men_media = x<media
men_media

array([ True,  True, False, False, False, False,  True, False,  True,
       False])

In [84]:
#x[men_media] = 0

In [85]:
#x

In [86]:
x[x < x.mean()] = 0
x

array([0.        , 0.        , 0.6030984 , 0.8622993 , 0.65849341,
       0.95489476, 0.        , 0.63479552, 0.        , 0.68867759])

In [87]:
nx = x[x > 0]
nx

array([0.6030984 , 0.8622993 , 0.65849341, 0.95489476, 0.63479552,
       0.68867759])

In [88]:
nx[0] = -10
nx

array([-10.        ,   0.8622993 ,   0.65849341,   0.95489476,
         0.63479552,   0.68867759])

In [89]:
x

array([0.        , 0.        , 0.6030984 , 0.8622993 , 0.65849341,
       0.95489476, 0.        , 0.63479552, 0.        , 0.68867759])