# Computations with numpy

## The slowness of loops

In [2]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [3]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

1.45 s ± 43.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [5]:
%timeit (1.0 / big_array)

3.45 ms ± 106 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
x = np.arange(5)
y = np.arange(1, 6)

print(x)
print(y)
print(x/y)

[0 1 2 3 4]
[1 2 3 4 5]
[0.         0.5        0.66666667 0.75       0.8       ]


In [7]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

## Basic Ufuncs

|Operator|	Equivalent ufunc |	Description |
|---:|:-------------| :-------------|
|+ |	np.add|	Addition (e.g., 1 + 1 = 2) |
|- |	np.subtract |	Subtraction (e.g., 3 - 2 = 1) |
|- |	np.negative |	Unary negation (e.g., -2) |
|* |	np.multiply |	Multiplication (e.g., 2 * 3 = 6)|
|/ |	np.divide |	Division (e.g., 3 / 2 = 1.5)|
|// |	np.floor_divide |	Floor division (e.g., 3 // 2 = 1)|
|** |	np.power |	Exponentiation (e.g., 2 ** 3 = 8)|
|% |	np.mod |	Modulus/remainder (e.g., 9 % 4 = 1)|

## Agreggates

In [8]:
x = np.arange(1, 10)
print(x)
print(np.add.reduce(x))

[1 2 3 4 5 6 7 8 9]
45


In [9]:
np.multiply.reduce(x)

362880

In [10]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [11]:
np.multiply.accumulate(x)

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880])

In [12]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [13]:
L = np.random.random(100)
sum(L)

50.461758453195614

In [14]:
np.sum(L)

50.46175845319564

In [15]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

71.8 ms ± 3.08 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.47 ms ± 90.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [16]:
min(big_array), max(big_array)

(7.071203171893359e-07, 0.9999997207656334)

In [17]:
np.min(big_array), np.max(big_array)

(7.071203171893359e-07, 0.9999997207656334)

In [18]:
%timeit min(big_array)
%timeit np.min(big_array)

46.1 ms ± 1.35 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
620 µs ± 25.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [19]:
print(big_array.min(), big_array.max(), big_array.sum())

7.071203171893359e-07 0.9999997207656334 500216.8034810001


## Multi-dimensional aggregates

In [20]:
M = np.random.randint(0,9,(3,4))
print(M)

[[0 8 1 3]
 [3 7 4 8]
 [4 5 1 3]]


In [21]:
M.sum()

47

In [22]:
M.sum(axis=0)

array([ 7, 20,  6, 14])

In [23]:
M.sum(axis=1)

array([12, 22, 13])

In [24]:
M.min()

0

In [25]:
M.min(axis=0)

array([0, 5, 1, 3])

## Other aggregates

|Function Name|	NaN-safe Version|	Description|
|:-----|:----------|:-------------|
|np.sum|	np.nansum|	Compute sum of elements|
|np.prod|	np.nanprod|	Compute product of elements|
|np.mean|	np.nanmean|	Compute mean of elements|
|np.std|	np.nanstd|	Compute standard deviation|
|np.var|	np.nanvar|	Compute variance|
|np.min|	np.nanmin|	Find minimum value|
|np.max|	np.nanmax|	Find maximum value|
|np.argmin|	np.nanargmin|	Find index of minimum value|
|np.argmax|	np.nanargmax|	Find index of maximum value|
|np.median|	np.nanmedian|	Compute median of elements|
|np.percentile|	np.nanpercentile|	Compute rank-based statistics of elements|
|np.any|	N/A|	Evaluate whether any elements are true|
|np.all|	N/A|	Evaluate whether all elements are true|

## Logical operations

In [26]:
x = np.array([1, 2, 3, 4, 5])

In [27]:
x < 3  # less than

array([ True,  True, False, False, False])

In [28]:
x > 3  # greater than

array([False, False, False,  True,  True])

In [29]:
x <= 3  # less than or equal

array([ True,  True,  True, False, False])

In [30]:
x != 3  # not equal

array([ True,  True, False,  True,  True])

In [31]:
x == 3  # equal

array([False, False,  True, False, False])

In [32]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False])

In [33]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [34]:
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [35]:
# how many values less than 6?
np.count_nonzero(x < 6)

8

In [36]:
np.sum(x < 6)

8

In [37]:
# how many values less than 6 in each row?
np.sum(x < 6, axis=1)

array([4, 2, 2])

In [38]:
# are there any values greater than 8?
np.any(x > 8)

True

In [39]:
np.any(x < 0)

False

In [40]:
np.all(x == 6)

False

In [41]:
np.all(x >= 0)

True

In [42]:
np.all(x < 8, axis=1)

array([ True, False,  True])

### Boolean operations

In [52]:
x = np.random.randint(20,size=(1,10))
x

array([[ 4, 16,  4,  4,  0,  5, 15, 10, 18,  2]])

In [53]:
np.sum((x > 3) & (x < 5))

3

In [54]:
np.sum(~((x > 3) & (x < 5)))

7

In [55]:
np.sum(~( (x <= 3) | (x >= 5) ))

3

In [57]:
x < 5

array([[ True, False,  True,  True,  True, False, False, False, False,
         True]])

In [59]:
x[x < 5]

array([4, 4, 4, 0, 2])

### Fancy indexing

In [ ]:
x = np.random.randint(100, size=(10))
print(x)

In [ ]:
[x[3], x[7], x[2]]

In [ ]:
ind = [3, 7, 4]
x[ind]

In [ ]:
X = np.arange(12).reshape((3, 4))
X

In [ ]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col]

In [ ]:
X[2, [2, 0, 1]]

In [ ]:
X = np.arange(20).reshape((10, 2))

In [ ]:
indices = np.random.choice(X.shape[0], 5, replace=False)
indices

In [ ]:
selection = X[indices]  # fancy indexing here
print(selection)
print(selection.shape)

## Exercícios

1. Crie um array numpy de forma (3, 3) com elementos aleatórios entre 1 e 10. Em seguida, calcule a média dos elementos desse array.
2. Crie um array numpy de forma (4, 4) com elementos aleatórios entre 1 e 100. Em seguida, calcule a soma de todos os elementos do array.
3. Crie um array numpy de forma (5, 5) com elementos aleatórios entre 1 e 10. Em seguida, calcule a soma dos elementos em cada coluna do array.

### Exercícios operações lógicas e booleanas

1. Crie um array numpy aleatório com forma (5, 5) e encontre todos os elementos maiores que 0, mas menores que 5.
2. Crie dois arrays numpy aleatórios com forma (3, 3) e encontre todos os elementos que estão presentes em ambos os arrays.
3. Crie um array numpy aleatório com forma (10,) e substitua todos os elementos que são menores que a média do array por 0 e todos os outros elementos por 1.

In [ ]:
import numpy as np

# Cria um array numpy aleatório com forma (5, 5)
arr = np.random.randint(low=-5, high=10, size=(5, 5))

# Encontra todos os elementos maiores que 0, mas menores que 5
filtro = (arr > 0) & (arr < 5)
resultados = arr[filtro]
print(resultados)


In [ ]:
import numpy as np

# Cria dois arrays numpy aleatórios com forma (3, 3)
arr1 = np.random.randint(low=0, high=10, size=(3, 3))
arr2 = np.random.randint(low=0, high=10, size=(3, 3))

# Encontra todos os elementos que estão presentes em ambos os arrays
intersecao = np.intersect1d(arr1, arr2)
print(intersecao)


In [ ]:
import numpy as np

# Cria um array numpy aleatório com forma (10,)
arr = np.random.randint(low=-5, high=10, size=(10,))

# Substitui todos os elementos menores que a média por 0 e outros por 1
media = np.mean(arr)
arr[arr < media] = 0
arr[arr >= media] = 1
print(arr)


### Fancy indexing

1. Crie um array numpy 2D com forma (4, 4) com valores aleatórios de 1 a 16 e use o fancy indexing para selecionar os elementos nas posições (0, 0), (1, 1), (2, 2) e (3, 3).

2. Crie um array numpy 2D com forma (5, 5) com valores aleatórios de 0 a 9 e use o fancy indexing para selecionar os elementos nas posições (0, 1), (1, 2), (2, 3) e (3, 4).

In [ ]:
import numpy as np

# Cria um array numpy 2D com forma (4, 4) com valores aleatórios de 1 a 16
arr = np.random.randint(low=1, high=17, size=(4, 4))

# Usa o fancy indexing para selecionar os elementos nas posições (0, 0), (1, 1), (2, 2) e (3, 3)
indices = [0, 1, 2, 3]
resultados = arr[indices, indices]
print(resultados)


In [ ]:
import numpy as np

# Cria um array numpy 2D com forma (5, 5) com valores aleatórios de 0 a 9
arr = np.random.randint(low=0, high=10, size=(5, 5))

# Usa o fancy indexing para selecionar os elementos nas posições (0, 1), (1, 2), (2, 3) e (3, 4)
indices = [[0, 1], [1, 2], [2, 3], [3, 4]]
resultados = arr[indices]
print(resultados)


### Desafio

Análise de dados meteorológicos: Suponha que você tenha dados de temperatura em um array numpy de forma (360, 24), onde cada linha representa um dia do ano e cada coluna representa uma hora do dia (assumindo que todos os mese tem 30 dias). 
1. Gere os dados de forma aleatória utilizando números inteiros entre 20 e 40. 
2. Use numpy para calcular a temperatura média e a temperatura mais alta para cada mês. 
3. Conte em quantos dias por mês a temperatura foi maior do que 30 graus.

In [ ]:
import numpy as np

# Cria um array numpy de temperatura aleatório
temperatura = np.random.randint(low=20, high=40, size=(360, 24))

# Calcula a temperatura média para cada mês
media_mensal = np.mean(temperatura.reshape(12, 24*30), axis=1)

# Calcula a temperatura máxima para cada mês
max_mensal = np.max(temperatura.reshape(12, 24*30), axis=1)

# Exibe a temperatura média e máxima para cada mês
meses = ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez']
for i in range(12):
    print(f'Temperatura média para {meses[i]}: {media_mensal[i]:.2f}°C')
    print(f'Temperatura máxima para {meses[i]}: {max_mensal[i]}°C')